import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { LucideIcon } from "lucide-react";
import {
  ArrowRight,
  Sparkles,
  Brain,
  Globe,
  Search,
  FileText,
  Plug,
  Share2,
  BarChart3,
  Network,
  CalendarDays,
  Code2,
  CheckCircle2,
  Zap,
  ImageIcon,
  Link2,
  Tags,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Features | StackSerp AI Content & SEO Platform",
  description:
    "Explore StackSerp's powerful features: AI content generation, multi-website management, automated internal linking, CMS integrations, and programmatic SEO.",
  keywords: "StackSerp features, AI SEO tools, programmatic SEO software, automated content creation",
  openGraph: {
    title: "StackSerp Features | Automate Your SEO",
    description:
      "From keyword clustering to one-click CMS publishing, discover how StackSerp replaces your entire content team.",
    type: "website",
    url: "https://stackserp.com/features",
  },
  alternates: {
    canonical: "https://stackserp.com/features",
  },
};

const features: { icon: LucideIcon; title: string; description: string; bullets: string[] }[] = [
  {
    icon: Brain,
    title: "AI Content Generation",
    description: "7-step pipeline: research, outline, draft, tone match, SEO optimize, metadata, and featured image.",
    bullets: ["Real-time web research", "Brand voice matching", "1,500–2,500 word articles", "AI-generated featured image"],
  },
  {
    icon: Globe,
    title: "Multi-Website Management",
    description: "One dashboard for all your websites — each with its own keywords, settings, and publishing schedule.",
    bullets: ["Separate keyword queues", "Individual brand voices", "Per-site analytics", "Team permissions"],
  },
  {
    icon: Search,
    title: "SEO Engine",
    description: "Every post is automatically optimized with meta tags, structured data, and on-page SEO scoring.",
    bullets: ["Auto meta titles & descriptions", "JSON-LD schema markup", "Content quality scoring", "IndexNow indexing"],
  },
  {
    icon: Plug,
    title: "CMS Integrations",
    description: "Push finished posts directly to WordPress, Ghost, Shopify, Webflow, or any platform via webhook.",
    bullets: ["WordPress REST API", "Ghost & Shopify support", "Webflow CMS collections", "Custom webhooks"],
  },
  {
    icon: Link2,
    title: "Internal Linking Engine",
    description: "Automatically suggests and inserts contextual internal links to boost your site's link equity.",
    bullets: ["Keyword-to-URL mapping", "Auto-insert in new posts", "Avoids duplicate links", "Manual link overrides"],
  },
  {
    icon: Network,
    title: "Topic Clusters",
    description: "AI plans your entire content strategy — pillar pages and supporting articles that build topical authority.",
    bullets: ["Pillar + cluster generation", "Auto internal link mapping", "Topical authority scoring", "Cluster analytics"],
  },
  {
    icon: Share2,
    title: "Social Publishing",
    description: "Automatically share new posts on Twitter/X and LinkedIn with platform-optimized captions.",
    bullets: ["Twitter/X auto-posting", "LinkedIn auto-sharing", "Captions per platform", "Scheduled social posts"],
  },
  {
    icon: BarChart3,
    title: "Analytics",
    description: "Connect Google Search Console and track traffic, rankings, and content performance in real time.",
    bullets: ["Search Console integration", "Per-post traffic data", "Keyword ranking tracking", "Monthly reports"],
  },
  {
    icon: CalendarDays,
    title: "Content Calendar",
    description: "Visual calendar showing your entire content pipeline — scheduled, in-progress, and published.",
    bullets: ["Month / week / day views", "Drag-and-drop scheduling", "Multi-site overlay", "Bulk scheduling"],
  },
  {
    icon: Code2,
    title: "Public REST API",
    description: "Automate everything programmatically — create posts, trigger generation, pull analytics.",
    bullets: ["API key auth", "Webhook events", "All dashboard features via API", "Full documentation"],
  },
  {
    icon: ImageIcon,
    title: "AI Image Generation",
    description: "Every post gets a unique, high-quality featured image generated by Imagen and uploaded automatically.",
    bullets: ["Gemini + Imagen pipeline", "Niche-aware style selection", "1200×630 WebP output", "Custom prompt override"],
  },
  {
    icon: Tags,
    title: "Metadata & Schema",
    description: "Auto-generated SEO metadata and structured data for every post — including social captions.",
    bullets: ["Meta title & description", "Article schema markup", "Twitter + OG tags", "Social captions for 4 platforms"],
  },
];

const pipeline = [
  { step: "01", label: "Research", desc: "Real-time competitor & web analysis" },
  { step: "02", label: "Outline", desc: "Structured H2/H3 content plan" },
  { step: "03", label: "Draft", desc: "Full long-form article written" },
  { step: "04", label: "Tone", desc: "Brand voice refinement pass" },
  { step: "05", label: "SEO", desc: "Keywords, links & structure optimized" },
  { step: "06", label: "Metadata", desc: "Meta tags, schema & social captions" },
  { step: "07", label: "Image", desc: "AI-generated featured image" },
];

export default function FeaturesPage() {
  return (
    <>
      {/* Hero */}
      <section className="py-20 md:py-28 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <Badge variant="outline" className="mb-6 px-4 py-1.5 text-sm">
            <Sparkles className="mr-1 h-3 w-3" />
            Full Feature Set
          </Badge>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
            Everything you need to{" "}
            <span className="text-primary">dominate search</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
            One platform replaces your entire content marketing stack — from research to published, promoted, and tracked.
          </p>
          <div className="flex items-center justify-center gap-3">
            <Button asChild size="lg">
              <Link href="/register">
                Start for Free <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline">
              <Link href="/pricing">View Pricing</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* 7-step pipeline */}
      <section className="pb-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <Badge variant="outline" className="mb-3 px-3 py-1 text-xs">
              <Zap className="mr-1 h-3 w-3" />
              AI Pipeline
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold">From keyword to published in 7 steps</h2>
            <p className="text-muted-foreground mt-2">Every post goes through the full pipeline automatically</p>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-7 gap-3">
            {pipeline.map((p, i) => (
              <div key={p.step} className="relative flex flex-col items-center text-center gap-2">
                {i < pipeline.length - 1 && (
                  <div className="hidden md:block absolute top-5 left-[calc(50%+20px)] right-[-calc(50%-20px)] h-px bg-border w-full" />
                )}
                <div className="h-10 w-10 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center text-xs font-bold text-primary z-10 bg-background">
                  {p.step}
                </div>
                <p className="text-xs font-semibold">{p.label}</p>
                <p className="text-xs text-muted-foreground leading-tight hidden sm:block">{p.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Feature Grid */}
      <section className="pb-24 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-3">All features at a glance</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Everything StackSerp does — no fluff, no filler.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f) => {
              const Icon = f.icon;
              return (
                <div
                  key={f.title}
                  className="rounded-xl border bg-card p-5 flex flex-col gap-3 hover:shadow-sm transition-shadow"
                >
                  <div className="flex items-center gap-3">
                    <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                      <Icon className="h-4.5 w-4.5 text-primary" style={{ height: "1.125rem", width: "1.125rem" }} />
                    </div>
                    <div>
                      <p className="font-semibold text-sm leading-tight">{f.title}</p>
                    </div>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed">{f.description}</p>
                  <ul className="space-y-1.5 mt-auto">
                    {f.bullets.map((b) => (
                      <li key={b} className="flex items-start gap-2 text-xs text-muted-foreground">
                        <CheckCircle2 className="h-3.5 w-3.5 text-green-500 shrink-0 mt-0.5" />
                        {b}
                      </li>
                    ))}
                  </ul>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-muted/30 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to automate your content marketing?
          </h2>
          <p className="text-lg text-muted-foreground mb-8">
            Start free — no credit card required. Your first 5 posts are on us.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <Button asChild size="lg" className="text-base px-8 h-12">
              <Link href="/register">
                Get Started Free
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="text-base px-8 h-12">
              <Link href="/pricing">View Pricing</Link>
            </Button>
          </div>
        </div>
      </section>
    </>
  );
}
